# Generated by Django 2.1.7 on 2019-09-27 11:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_desc',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
